version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    networks:
      - app-net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:9092,
        PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "29092:29092"
    expose:
      - "9092"

  redis:
    image: redis:7.0-alpine
    ports: ["6379:6379"]
    networks:
      - app-net

  fe_app:
    build: .
    command: ["faust", "-A", "fe.fe_app:app", "worker", "-l", "info"]
    depends_on: [kafka, redis]
    environment:
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis
    networks:
      - app-net

networks:
  app-net:
